### ISSUE TITLE
Authentication fails between Grafana and InfluxDB

### ISSUE THREAD

**Issue by janniksinz** [raynigon/ping-monitor#4]
An error occurred within the plugin
```
message: "an error occurred within the plugin"
messageId: "plugin.downstreamError"
```

Authentication to data source failed
```
message: "InfluxDB Error: Bad Request"
data: Object
  message: "Authentication to data source failed"
config: Object
  method: "GET"
  url: "api/datasources/proxy/uid/P951FEA4DE68E13C5/query"
```

I suspect this change to be the cause:
https://stackoverflow.com/questions/67447251/grafana-influx-db-authentication-to-data-source-failed

**Comment by raynigon** [comment]
Thank you for the issue.

I just pinned the InfluxDB Version which should fix this issue.
In the long term another DB is needed for this since InfluxDB is too complex in such an small setup.
