### ISSUE TITLE
generate.py does not generate .env file

### ISSUE THREAD

**Issue by fredagsguf** [raynigon/ping-monitor#5]
Hi,

generate.py does not generate .env file where the password for grafana is stored, am i supposed to create it myself?

**Comment by raynigon** [comment]
Could you attach a screenshot or console output please?
Informations about your system setup, os, python version, etc. would also be nice to have.

**Comment by fredagsguf** [comment]
> Could you attach a screenshot or console output please? Informations about your system setup, os, python version, etc. would also be nice to have.

There is none console output, i don't know where to set the password for grafana.
OS: Ubuntu 22.04
python: 3.8

Followed the "guide" step by step on the frontpage.

There's supposed to be a .env file here right?
![image](https://github.com/raynigon/ping-monitor/assets/46964809/7e75c51c-b913-41cd-a1fd-b63d3ca8a370)

**Comment by raynigon** [comment]
Please try `ls -lisa` and check if the file was generated.
I will look into this tomorrow.

**Comment by fredagsguf** [comment]
Apparently it was hidden, i found it - thanks!

**Comment by fredagsguf** [comment]
Hmm something is wrong, i tried deleting the folder and rebuild it then use the password - however i can't login still.
Even though i use the password from the .env file.
Do you have any ideas if something is holding onto the old password?

**Comment by janniksinz** [comment]
@Laukage
`docker exec` into the grafana docker container.
Get the docker name with `docker ps`.
Something like `docker exec -it <docker name>`
Use the `grafana-cli` to change your password manually. 
`sudo grafana-cli admin reset-admin-password pwd123`

You don't have to do this every time since it's stored in the volume.

**Comment by fredagsguf** [comment]
> @Laukage `docker exec` into the grafana docker container. Get the docker name with `docker ps`. Something like `docker exec -it <docker name>` Use the `grafana-cli` to change your password manually. `sudo grafana-cli admin reset-admin-password pwd123`
> 
> You don't have to do this every time since it's stored in the volume.

Thank you that worked! :D
